### ISSUE TITLE
An item that is inserted in the middle of a checklist does not get saved

### ISSUE THREAD

**Issue by w-k-s** [baggachipz/tinylist#10]
**Steps:**
1. Create a new checklist
2. Add item "First Item"
3. Add item "Second Item"
4. Close the modal dialogue and verify that the checklist is saved with two items.
5. Tap on the checklist card to modify.
6. Place cursor at end of first item, press return and verify that this inserts a new check list item between first and second item.
7. Write a note in the newly created middle item e.g. Middle Item
8. Press Close

**Expected behaviour**:
- Card displays the originally created first item and second item as well as the newly created middle item.

**Actual Behaviour**:
-  card displays a checklist that contains the first item, second item but not the newly created middle item.

**Test Device**
Safari on iPhone 8 (Running iOS 14.0.1)

**Comment by baggachipz** [comment]
I see that behavior too, I'll investigate.

**Comment by baggachipz** [comment]
Resolved in commit https://github.com/baggachipz/tinylist/commit/c54acea37d44ca13a8084f8414628c629359e6d3

Rapid successive update calls were resulting in a document conflict error in PouchDB. Throttled the onchange call to prevent this.
