### ISSUE TITLE
Unchecked Items sometimes appear checked...

### ISSUE THREAD

**Issue by ASNosal** [baggachipz/tinylist#11]
Occasionally, items that are unchecked (after being previously checked) appear as checked even though they are sorted as unchecked.

**Comment by baggachipz** [comment]
I've seen that too and have been trying to replicate it reliably so I can fix it. If you can reliably make it happen, please post that info here so that I can git it fixed up. Thanks for reporting!

**Comment by ASNosal** [comment]
I tried duplicating it a bunch of times this morning, but was unable to come up with steps to reliably re-produce it unfortunately - sorry!

**Comment by baggachipz** [comment]
I was able to duplicate the behavior and put out a fix. Please let me know if you still see the issue after a reload... thanks for reporting!
