### ISSUE TITLE
Google Keep Takeout zip file import failure

### ISSUE THREAD

**Issue by crendl** [baggachipz/tinylist#14]
When trying to import my takeout.zip file, the error I receive is the following:

`Unexpected token P in JSON at position 0`

Thanks!

**Comment by baggachipz** [comment]
Would you feel comfortable providing the file so that I can attempt the import myself? It must have some data which is in a format I haven't expected.

**Comment by crendl** [comment]
i'm puzzled, but i am actually not able to reproduce my import error; neither with the old takeout.zip, nor with a new one...
i'm closing the issue, since it works now!
