### ISSUE TITLE
Text overflows out of note

### ISSUE THREAD

**Issue by nalderto** [baggachipz/tinylist#16]
If the horizontal width is narrow enough, the text of the note with overflow out of the bounds of the note.  This appears primarily with the "Grid" view option when using heading level 1 with Markdown.  
![image](https://user-images.githubusercontent.com/25762130/107275446-bea5cf00-6a1f-11eb-95ca-13c23b24e5d7.png)

**Comment by crendl** [comment]
this also happens with words/sentences, which.are.very.long.and.are.not.separated.by.spaces; e.g. long file paths, etc.

it can be observed especially on the mobile app

**Comment by baggachipz** [comment]
Good catch, I'll work on a fix for this as soon as possible.
