### ISSUE TITLE
Reverse-proxy configuration steps

### ISSUE THREAD

**Issue by ericerkz** [baggachipz/tinylist#18]
I spent a solid five hours racking my brain/trying every which way to get this to work, both using the docker image and by compiling from source but the closest I could ever get to having tinylist work was when accessing via http without any SSL proxy. 

The second I enabled any sort of apache reverse proxy for SSL/HTTPS it would just get stuck on the getting started/creating database page. 

Would love to make this work, but is there some sort of compatability issue with reverse-proxies? I had zero issue setting couchdb, etc, set up otherwise.

**Comment by baggachipz** [comment]
I've never tried this with any sort of reverse-proxy in the middle. CouchDB handles all that for you automatically, so I'm not sure why it would be necessary. Is there a specific reason you want to do that?

**Comment by ericerkz** [comment]
Hey bagga,

Thanks for the reply. 

To contextualize, I am trying to run this on a server that is already running other web services via apache,  thus I needed a reverse proxy to pass traffic through to it on a different port if I want to achieve the end-goal of having this service be accessible via port 80 (which I do).

I handle https by using lets encrypt and redirecting all traffic through to https instead of http at in the virtualhost file in apache itself, which for my other services works just fine. 

More important nuance here though that is more the problem on the tinylist side I believe - even when I just passed traffic straight through to it, _without_ my https redirection (so straight http reqs, proxied to the appropriate port tinylist was running on) it would still just hang at the 'creating database' step similar to https://github.com/baggachipz/tinylist/issues/8

**Comment by baggachipz** [comment]
OK, I'll try to provide more information about this we can try to figure it out. The "Create Database" function is the one interesting wrinkle in the project. The function is found here: https://github.com/baggachipz/tinylist/blob/master/src/functions/create-database.js and it's separated out for a reason. In CouchDB, creating databases is at a different security level, and for good reason: If anybody can create databases, then a DB instance open to the world would be quite ripe for abuse. So, the normal user account that adds/deletes/etc in databases is not the same one who *creates* databases. I created that separate function which, in the reference implementation on Netlify, uses [Netlify Functions](https://docs.netlify.com/functions/overview/) to execute create-database as an admin user. 

When the code is in "prod" mode (that is, there is a "PROD" environment variable in the runtime), it expects a remote function URL to also be defined: https://github.com/baggachipz/tinylist/blob/master/src/utils.js#L14

If not in "prod" mode, it assumes "dev" mode and just includes the file and executes the "create database" call assuming the current user has sufficient privileges to do that. 

So, what error do you get in the js console on that "creating database..." page? That should give insight into what's happening, I hope.

**Comment by ericerkz** [comment]
Ahhhh, you highlighting that create-database.js made me realize something that wasn't clear - Is it using port 6894 instead of 5894 when it is set to be prod for the web ui to communicate back to couch?

**Comment by ericerkz** [comment]
Ah wait up, no, I see that's an OR statement to be definied port variable OR 6894... So not the rub. 
I will spin back up and check on what the JS is spitting out later today :). Thanks for the reply

**Comment by baggachipz** [comment]
Just to add some color:
HTTP -> 5984
HTTPS -> 6984
