### ISSUE TITLE
Any hopes on a Docker integration ?

### ISSUE THREAD

**Issue by guim31** [baggachipz/tinylist#2]
As I like to selfhost a lot and I'm using Unraid, the easyiest way is Docker....!

Do you have any plans on creating it ?

**Comment by baggachipz** [comment]
I know at least one person is currently working on getting that going, as soon as they do I'll happily add the Docker file to the repo for sure.

**Comment by guim31** [comment]
Happy to read that! I really want to try your app

**Comment by baggachipz** [comment]
[Docker instructions here.](https://github.com/baggachipz/tinylist/blob/master/Docker.md) Give it a try and feel free to contribute!

**Comment by quamok** [comment]
@guim31 were you able to set it up? I too am using unraid,  and I am having a hard time trying to set it up since no dockerhub image is available.

**Comment by baggachipz** [comment]
So would getting this on DockerHub help your situation?

**Comment by quamok** [comment]
In my case it would mean that I could install it on Unraid, yes. I'm very far from being a Docker expert, but I'm pretty sure this would speed up adoption (Unraid, Synology, etc) by increasing ease of deployment, if that's something you're looking for :)

**Comment by guim31** [comment]
Hi @quamok !

TBH I don't remember if I was able to do it, as my first need was the possibility of file attachement (pics / files) and it was not available at the time , so I didn't look further.

I'm absolutly sure that a docker template for Unraid would BOOST this project. I recently saw this with another project (gladysassistant) which statistics saw a really BIG increase the day it was available on Unraid.
The need is more a docker template for Unraid that a Dockerhub hosting btw.

I'm not a developper so I can't help sadly, but I hope this will be a possibility.

**Comment by quamok** [comment]
Thank you for your comment! From what I understand, the unraid template is based on a container image, usually available on dockerhub, and is only to make it easier to deploy on unraid specifically. It's still super easy to deploy a container image from dockerhub on unraid without a template just by mapping the proper paths and variables. 

I think by just making a container image available on dockerhub is enough, and would make tinylist available on all platforms using docker, including unraid. The unraid template would be the cherry on top.

**Comment by jeffxt** [comment]
> In my case it would mean that I could install it on Unraid, yes. I'm very far from being a Docker expert, but I'm pretty sure this would speed up adoption (Unraid, Synology, etc) by increasing ease of deployment, if that's something you're looking for :)

Nearly a year late to the party, but I second this!  I actually came over from reddit's r/selfhosted and discovered this app based on a recommendation in the comments.  I would say there are PLENTY of people who are seeking a note-taking app which is a direct Google Keep replacement, but with a focus on privacy (and this app even nails the UX!).  I believe this actually _is_ the perfect solution many are looking for, especially for those running a Synology NAS.  

That said, I was surprised to see this app isn't more popular, and I do believe that having an image on DockerHub would really help out less technical users, like me, to get this set up.  This would bring a lot more visibility to your project and push this app to the next level!

**Comment by baggachipz** [comment]
Thanks for the kind words! OK, I'll work on getting it on DockerHub. I completely forgot about this so the reminder is appreciated 🤦

**Comment by jeffxt** [comment]
> Thanks for the kind words! OK, I'll work on getting it on DockerHub. I completely forgot about this so the reminder is appreciated 🤦

Not a problem, thanks for the incredibly fast reply lol.  And while I might not be able to provide any technical help, I'd be happy to help be an advocate and spread the word.  Also, as a product manager in my professional life, I understand how much it takes / how much it costs to build apps, so also happy to donate if that would help :)

**Comment by baggachipz** [comment]
As an update, I won't be adding this to the Docker Registry until the whole [kerfuffle around open source](https://blog.alexellis.io/docker-is-deleting-open-source-images/) is solved. If it's not solved, there can't be a Docker Registry entry for Tinylist 😢

**Comment by jeffxt** [comment]
> As an update, I won't be adding this to the Docker Registry until the whole [kerfuffle around open source](https://blog.alexellis.io/docker-is-deleting-open-source-images/) is solved. If it's not solved, there can't be a Docker Registry entry for Tinylist 😢

Oh wow, that's really disappointing on Docker's part.  I'd completely understand if I were in your position, and it would be really unfortunate if this is not resolved with the community.  

Looks like [Docker posted an update as of 3/17](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) - is your account one of the ones affected?

**Comment by baggachipz** [comment]
> > As an update, I won't be adding this to the Docker Registry until the whole [kerfuffle around open source](https://blog.alexellis.io/docker-is-deleting-open-source-images/) is solved. If it's not solved, there can't be a Docker Registry entry for Tinylist 😢
> 
> Oh wow, that's really disappointing on Docker's part. I'd completely understand if I were in your position, and it would be really unfortunate if this is not resolved with the community.
> 
> Looks like [Docker posted an update as of 3/17](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) - is your account one of the ones affected?

I'm really not sure yet. This whole thing needs to settle out. I can say that I won't be paying them any money for this, that much I know. :)
