### ISSUE TITLE
Android widget

### ISSUE THREAD

**Issue by ruijpbastos** [baggachipz/tinylist#22]
Would be great to have an Android widget that showed recent notes (or that allowed to scroll through all notes). This would be even more helpful with the archiving option I wishfully asked for in #21 , as it could show only un-archived notes!

**Comment by baggachipz** [comment]
Is an Android widget even possible with a PWA? I'm not an android expert (haven't developed for it in years) so I'm not sure what is possible nowadays.

**Comment by ruijpbastos** [comment]
Ah, guess not: https://bugs.chromium.org/p/chromium/issues/detail?id=1170639 !

**Comment by baggachipz** [comment]
Oh well :(
