### ISSUE TITLE
Icon camouflages with the background in dark mode

### ISSUE THREAD

**Issue by Sahil2004** [baggachipz/tinylist#4]
This happens on windows 10 and android. As my wallpaper is also dark, it becomes very difficult to find the icon. 

Example (on windows 10 taskbar):
![image](https://user-images.githubusercontent.com/40143545/93710732-7700d280-fb66-11ea-91ba-ff741d780ed3.png)

**Comment by baggachipz** [comment]
I'll be adding more support for dark mode in upcoming releases.
