### ISSUE TITLE
enhancement: import txt files

### ISSUE THREAD

**Issue by simonmcnair** [baggachipz/tinylist#44]
I have a pile of notepad files, it would be ace to import them.  Is it possible pls ?

**Comment by baggachipz** [comment]
I could work on that. Would it be each file becoming one note?

**Comment by simonmcnair** [comment]
Yeah, I reckon so.  I think this would be a reasonably common use case.  I have a stockpile of snippets I'd love to get shot of

**Comment by baggachipz** [comment]
Ok, let me see what I can do. Probably could enhance the existing import to allow just text files (or a zip of text files) and that wouldn't be tough.

**Comment by simonmcnair** [comment]
I hoped and thought it would be simpler than google takeout ;-)

**Comment by simonmcnair** [comment]
out of curiosity what is the export format pls ?  what can it be imported in to ?

**Comment by baggachipz** [comment]
It's zip export of one json file per note/checklist. The format is what CouchDB uses for its documents.

**Comment by baggachipz** [comment]
I've added the ability to import `.txt` files, both individually and if they're in a zip file. Hope this helps you!
