### ISSUE TITLE
Deleting an item from a checklist won't persist the deletion

### ISSUE THREAD

**Issue by RiccardoCampo** [baggachipz/tinylist#47]
**Browser:** Firefox 111.0.1

**Issue**: When deleting an item from a checklist, using the **X** button, the item is deleted from the edit view, but when the edit view is closed the deleted items pops back in in the checklist.

![immagine](https://user-images.githubusercontent.com/22866548/232615018-0188aadf-9981-4257-b10f-112c2c6d0766.png)

**Possible solution**:  I think the `EditChecklist` component method `deleteItem` ([here](https://github.com/baggachipz/tinylist/blob/abc8a66304308d73353bc55d2bb3935db6c11a4f/src/components/Checklist/EditChecklist.vue#L129-L131)) is missing a `this.onChange()` call

**Comment by baggachipz** [comment]
Good catch, I'm looking into it.
