### ISSUE TITLE
This looks soo empty

### ISSUE THREAD

**Issue by Sahil2004** [baggachipz/tinylist#5]
Hey, like google keep the logo can be put in the center to fill it up. It ould be great.
![image](https://user-images.githubusercontent.com/40143545/93710889-8b919a80-fb67-11ea-871e-399d5b53f917.png)

**Comment by baggachipz** [comment]
Believe it or not, this was a design decision by me. I want it to look empty with the only piece of the UI leading the user to create their first note. I *want* it to look empty so that they'll want to fill it up! :)
