### ISSUE TITLE
Selecting two items within 500ms will keep one of them selected but not checked

### ISSUE THREAD

**Issue by RiccardoCampo** [baggachipz/tinylist#53]
**Browser:** Firefox 118.0.2 (64 bit)

**Issue:** When selecting two checkboxes in a checklist within 500ms, one of them will display as _selected_ but not _checked_: meaning it will appear in the list of not checked items but with the ✔️ mark.

![immagine](https://github.com/baggachipz/tinylist/assets/22866548/638bc659-670a-4505-bcd9-b0d2f0e64132)

**Source of the issue:** (Maybe) In [here](https://github.com/baggachipz/tinylist/blob/9a0e9c693798f9d28b87b950c51c65a2e22fc6c4/src/components/Checklist/ViewChecklist.vue#L66-L72) the item is first set to _selected_ and after 500ms to _checked_. [Here](https://github.com/baggachipz/tinylist/blob/9a0e9c693798f9d28b87b950c51c65a2e22fc6c4/src/components/Checklist/ViewChecklist.vue#L8C23-L8C53) only the _checked_ items are rendered. So, when the first selected item times out, the refresh will destroy the second element (which is still waiting to be checked), resulting in it never being checked.

[Similar issue here](https://stackoverflow.com/questions/64760793/using-emit-multiple-times-separated-by-settimeout-in-vue-not-working-as-expecte)

**Possible solutions:**
1. Add another flag `isChanging`, to be set right away in `onChecked` and reset after the timeout. Change `uncheckedItems` to display also items with `isChanging`
2. Decrease the timeout to make this problem less frequent

**Comment by baggachipz** [comment]
The reason I put in the 500ms delay is because that's how long it takes the check animation to play. Prior to that, there was no visual indication that the item was checked; it would instantly move to the "checked" area and was a poor experience. But I like your idea and see the bug, so I'll work on that. Thanks!
