### ISSUE TITLE
Feature Request: Add possibility to hide/collapse checked items from the checklist View

### ISSUE THREAD

**Issue by RiccardoCampo** [baggachipz/tinylist#54]
Right now, only in the edit view of a checklist the checked items appear as collapsed, that is not the case outside of the edit view

_EDIT_ <img src="https://github.com/baggachipz/tinylist/assets/22866548/17c5c8f5-f275-440f-843b-7b66e1bc90f1" width="200" />      _VIEW_ <img src="https://github.com/baggachipz/tinylist/assets/22866548/3a0d08f3-0e20-48f1-ae77-d6f5d8c24f91" width="200" />

This is a bit annoying if you keep a shopping list with 50+ items in your homepage, it will fill up all the space with checked items

**Comment by baggachipz** [comment]
Good idea, I'll work on this.
